# Generated by Django 3.1.1 on 2020-09-24 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales', models.IntegerField()),
                ('total_food_cost', models.IntegerField()),
                ('tables_sat', models.IntegerField()),
                ('meals_served', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Entree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('menu_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('quantity_in_fridge', models.IntegerField()),
                ('portion_per_case', models.IntegerField()),
                ('price_per_case', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Side',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('menu_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('bill_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IngredientInSide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_in_side', to='project2App.ingredient')),
                ('side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_in_side', to='project2App.side')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientInEntree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_in_entree', to='project2App.entree')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_in_entree', to='project2App.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='FoodForTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_for_table', to='project2App.entree')),
                ('side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_for_table', to='project2App.side')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_for_table', to='project2App.table')),
            ],
        ),
    ]
